import Head from "next/head";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Github Search</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>
          <a href="https://nextjs.org">Github Search</a>
        </h1>

        <p>
          <code>first next.js project</code>
        </p>
      </main>
    </div>
  );
}
